### ISSUE TITLE
The Higher Ed. sample Portal is down

### ISSUE THREAD

**Issue by danikahil** [microsoft/Industry-Accelerator-Education#18]
Hi Team,
Unfortunately the Higher Ed. Portal is down since a couple of days.
https://hiedacceleratortd.powerappsportals.com

Could you resptore it if possible?

Thanks,
Dani

**Comment by srinirn** [comment]
Can we get the portal code/configuration files, as it will be useful for building further and in the demos as well.

**Comment by srinirn** [comment]
> Hi Team,
> Unfortunately the Higher Ed. Portal is down since a couple of days.
> https://hiedacceleratortd.powerappsportals.com
> 
> Could you resptore it if possible?
> 
> Thanks,
> Dani

Hi Dani,
I had been through your demo on powerplatform24 for the HigherEd. and it was good. 
The new portal is https://hiedacceleratordemo.powerappsportals.com/

Regards,
Srini

**Comment by danikahil** [comment]
Thanks Team.

Regards,
Dani
