### ISSUE TITLE
EducationAccelerator.Walkthrough.Guide.docx under documentation is not accessible

### ISSUE THREAD

**Issue by wedmondson** [microsoft/Industry-Accelerator-Education#28]
EducationAccelerator.Walkthrough.Guide.docx under documentation is not accessible. It requires account permissions to open. Should this file have access controls on it?

![Screenshot 2022-07-08 125421](https://user-images.githubusercontent.com/5130113/178045111-ddc7a425-7e65-4054-9497-f9aebf8964db.png)
![Screenshot 2022-07-08 125500](https://user-images.githubusercontent.com/5130113/178045117-4abcc3ca-8dc1-4a0f-a063-2ba205787078.png)

**Comment by ugreg** [comment]
@wedmondson this should be fixed in #29 

Please confirm.

**Comment by wedmondson** [comment]
This is fixed
